[package]
name = "local-hosting"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
anyhow = "1.0"
rand = "0.8.4"


# actix = "0.12"
actix-web = "3.3.2"
actix-service = "1.0.6"