[package]
name = "localhosting"
version = "0.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
anyhow = "1.0"
rand = "0.8.4"

actix-web = "3.3.2"
actix-service = "1.0.6"

faccess = "0.2.3"